import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "../components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of PortfoliAI.",
};

export default function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="[DD Month YYYY]">
      <p className="text-[14px] leading-[1.75]" style={{ color: "#4a4642" }}>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of
        PortfoliAI (&quot;we&quot;, &quot;us&quot;), which is currently operated on an
        individual basis as an early-stage, free beta and is not yet a registered company —
        these Terms will be updated with formal entity details once one is incorporated. This
        is a draft reviewed for a beta release; remaining bracketed placeholders should still
        be confirmed with qualified legal counsel before wider public launch.
      </p>

      <LegalSection heading="1. Acceptance of terms">
        <p>
          By creating an account or using PortfoliAI, you agree to be bound by these Terms
          and our Privacy Policy. If you do not agree, do not use the Service.
        </p>
      </LegalSection>

      <LegalSection heading="2. Description of the service">
        <p>
          PortfoliAI lets you upload investment transaction data (via broker export files or
          manual entry) and generates automated portfolio analysis reports (performance,
          cost, risk, and allocation metrics) in PDF form. Financial Advisors may generate
          reports on behalf of their clients.
        </p>
      </LegalSection>

      <LegalSection heading="3. Not financial advice">
        <p>
          Reports generated by PortfoliAI are provided for informational and educational
          purposes only and do not constitute financial, investment, tax, or legal advice, a
          personalized investment recommendation, or an offer or solicitation to buy or sell
          any financial instrument, under MiFID II (Directive 2014/65/EU) or any equivalent
          local regulation. PortfoliAI is not a licensed investment firm, financial advisor,
          or intermediary authorized by CONSOB or any other regulator, and using the Service
          does not create an advisory or fiduciary relationship between you and us. You are
          solely responsible for any decisions made based on a PortfoliAI report, and should
          consult a licensed, independent financial advisor before acting on it. Market data
          and calculations may contain errors or delays and should be independently verified
          before being relied upon.
        </p>
        <p>
          Some or all narrative sections of a report (e.g. risk commentary, allocation
          observations, strategic summaries) are generated automatically by an artificial
          intelligence model based on your data and general market data. AI-generated content
          may be inaccurate, incomplete, or based on outdated information, and does not
          reflect the judgment of a human advisor. You should treat it as a starting point for
          your own research, not as a conclusion to act on.
        </p>
      </LegalSection>

      <LegalSection heading="4. Accounts and eligibility">
        <p>
          You must provide accurate information when creating an account and are responsible
          for maintaining the confidentiality of your credentials and any activity under your
          account. The Service is not directed at, and may not be used by, individuals under
          the age of <strong>18</strong>. By creating an account you confirm that you meet
          this age requirement.
        </p>
      </LegalSection>

      <LegalSection heading="5. Your data and content">
        <p>
          You retain ownership of the transaction data you upload. You represent that you
          have the right to upload it, and — if acting as a Financial Advisor — that you
          have obtained any consent required from your clients. You are responsible for the
          accuracy of the data you provide; PortfoliAI is not liable for reports generated
          from inaccurate or incomplete data.
        </p>
      </LegalSection>

      <LegalSection heading="6. Subscription plans">
        <p>
          PortfoliAI is offered under different subscription tiers, including a free tier
          with a limited number of monthly reports. Paid tiers, their pricing, and their
          features are described on our <strong>[Pricing]</strong> page and may change with
          reasonable notice. <strong>[Add billing, renewal, refund, and cancellation terms
          once paid plans are live.]</strong>
        </p>
      </LegalSection>

      <LegalSection heading="7. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Use the Service for any unlawful purpose or to upload data you don&apos;t have the right to process.</li>
          <li>Attempt to reverse-engineer, disrupt, or gain unauthorized access to the Service.</li>
          <li>Resell or redistribute the Service without our written consent.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="8. Intellectual property">
        <p>
          The Service, its design, and underlying technology are owned by the operator of the
          Service and protected by intellectual property laws. These Terms do not grant you
          any rights to our trademarks or branding.
        </p>
      </LegalSection>

      <LegalSection heading="9. Termination">
        <p>
          You may stop using the Service and delete your account at any time. We may suspend
          or terminate your access if you breach these Terms or misuse the Service.
        </p>
      </LegalSection>

      <LegalSection heading="10. Disclaimer of warranties">
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot;, without
          warranties of any kind, express or implied, including accuracy, availability, or
          fitness for a particular purpose.
        </p>
      </LegalSection>

      <LegalSection heading="11. Limitation of liability">
        <p>
          To the maximum extent permitted by law, the operator of the Service
          shall not be liable for any indirect, incidental, or consequential damages,
          including investment losses, arising from your use of the Service or reliance on
          any report it generates.
        </p>
      </LegalSection>

      <LegalSection heading="12. Governing law">
        <p>
          These Terms are governed by the laws of <strong>[Jurisdiction]</strong>, without
          regard to conflict-of-law principles. Any dispute shall be subject to the exclusive
          jurisdiction of the courts of <strong>[Jurisdiction]</strong>.{" "}
          <em>[Jurisdiction to be finalized as the Service&apos;s access footprint and legal
          structure are confirmed; the Service is currently accessible internationally without
          restriction.]</em>
        </p>
      </LegalSection>

      <LegalSection heading="13. Changes to these terms">
        <p>
          We may update these Terms from time to time. Material changes will be notified via
          the Service or by email before they take effect; continued use after that point
          constitutes acceptance of the updated Terms.
        </p>
      </LegalSection>

      <LegalSection heading="14. Contact">
        <p>
          Questions about these Terms can be sent to <strong>support@portfoliai.online</strong>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
